<?php

/*
define('REACH_FIELDS_FB_API', 'https://graph.facebook.com');
define('REACH_FIELDS_FB', 'http://facebook.com');
define('REACH_FIELDS_GOOGLE_API', 'https://graph.facebook.com');
define('REACH_FIELDS_GOOGLE', 'http://facebook.com');
define('REACH_FIELDS_TWITTER_API', 'http://api.twitter.com');
define('REACH_FIELDS_TWITTER', 'http://twitter.com');
*/


/**
 * Define the reach_social_field_points field.
 */

/**
 * @defgroup reach_social_field Example: Field Types API
 * @ingroup examples
 * @{
 * Examples using Field Types API.
 *
 * This is updated from Barry Jaspan's presentation at Drupalcon Paris,
 * @link http://acquia.com/community/resources/acquia-tv/intro-field-api-module-developers Video Presentation @endlink
 *
 * Providing a field requires:
 * - Defining a field:
 *   - hook_field_info()
 *   - hook_field_schema()
 *   - hook_field_validate()
 *   - hook_field_is_empty()
 *
 * - Defining a formatter for the field (the portion that outputs the field for
 *   display):
 *   - hook_field_formatter_info()
 *   - hook_field_formatter_view()
 *
 * - Defining a widget for the edit form:
 *   - hook_field_widget_info()
 *   - hook_field_widget_form()
 *
 * Our module defines the field in reach_social_field_field_info(),
 * reach_social_field_field_validate() and reach_social_field_field_is_empty().
 * reach_social_field_field_schema() is implemented in reach_social_field.install.
 *
 * Our module sets up a formatter in reach_social_field_field_formatter_info() and
 * reach_social_field_field_formatter_view(). These are the API hooks that present
 * formatted and themed output to the user.

 * And finally, our module defines the widet in
 * reach_social_field_field_widget_info() and reach_social_field_field_widget_form().
 * The widget is the form element used to receive input from the user
 * when the field is being populated.
 *
 * @see field_types
 * @see field
 */

/**
 * Return all of our services' metadata.
 */
function reach_social_field_services() {
  $services = array();
  
  $services['facebook'] = array(
    'profile' => array(
      'label' => 'Profile',
      'uri' => 'http://facebook.com/[id]',
      'api_uri' => 'https://graph.facebook.com/[id]',
    ),
    'page' => array(
      'label' => 'Page',
      'uri' => 'http://facebook.com/[id]',
      'api_uri' => 'https://graph.facebook.com/[id]',
    ),
    'event' => array(
      'label' => 'Event',
      'uri' => 'http://facebook.com/[id]',
      'api_uri' => 'https://graph.facebook.com/[id]',
    ),
    'link' => array(
      'label' => 'Link',
      'uri' => 'http://facebook.com/[id]',
      'api_uri' => 'https://graph.facebook.com/[id]',
    ),
    'photo' => array(
      'label' => 'Photo',
      'uri' => 'http://facebook.com/[id]',
      'api_uri' => 'https://graph.facebook.com/[id]',
    ),
  );
  
  $services['google'] = array(
    'profile' => array(
      'label' => 'Profile',
      'uri' => 'https://plus.google.com/[id]',
      //'api_uri' => 'https://plus.google.com/[id]',
    ),
    'event' => array(
      'label' => 'Event',
      'uri' => 'https://google.com/calendar/[id]',
      //'api_uri' => 'https://plus.google.com/[id]',
    ),
    'doc' => array(
      'label' => 'Document',
      //'uri' => 'https://google.com/calendar/[id]',
      //'api_uri' => 'https://plus.google.com/[id]',
    ),
    'spreadsheet' => array(
      'label' => 'Spreadsheet',
      //'uri' => 'https://plus.google.com/[id]',
      //'api_uri' => 'https://plus.google.com/[id]',
    ),
  );
  
  $services['twitter'] = array(
    'profile' => array(
      'label' => 'Profile',
      'uri' => 'http://twitter.com/[id]',
      //'api_uri' => 'https://plus.google.com/[id]',
    ),
    'tweet' => array(
      'label' => 'Tweet',
      //'uri' => 'https://google.com/calendar/[id]',
      //'api_uri' => 'https://plus.google.com/[id]',
    ),
  );
  
  $services['flickr'] = array(
    'profile' => array(
      'label' => 'Profile',
      'uri' => 'http://flickr.com/[id]',
      //'api_uri' => 'https://plus.google.com/[id]',
    ),
    'photo' => array(
      'label' => 'Photo',
      //'uri' => 'https://google.com/calendar/[id]',
      //'api_uri' => 'https://plus.google.com/[id]',
    ),
  );
  
  return $services;
}


/***************************************************************
 * Field Type API hooks
 ***************************************************************/

/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function reach_social_field_field_info() {
  return array(
    // We name our field as the associative name of the array.
    'reach_social_field' => array(
      'label' => t('Social Reference'),
      'description' => t('Create a connection to an entity (profile, photo, event) on a social networking service.'),
      'default_widget' => 'reach_social_field_text',
      'default_formatter' => 'reach_social_field_link',
      'property_type' => 'value',
      'getter' => 'entity_metadata_field_verbatim_get',
      'setter' => 'entity_metadata_field_verbatim_set',
    ),
    
  );
}



/**
 * Implements hook_field_widget_settings_form().
 */
function reach_social_field_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];
  
  $form['social'] = array(
    '#type' => 'fieldset', 
    '#description' => t('Typically you will select at least one of the two fields below:'),
  );
  
  $form['social']['service'] = array(
    '#type' => 'checkboxes', 
    '#title' => t('Service'), 
    '#description' => t('Select the social networking service(s) to allow for this field.'),
    '#default_value' => $settings['service'], 
    '#options' => _reach_social_field_get_services($settings['type']),
    '#multiple' => TRUE,
  );
  
  $form['social']['type'] = array(
    '#type' => 'checkboxes', 
    '#title' => t('Type'),
    '#description' => t('Select the type of item(s) to allow for this field.'),
    '#default_value' => $settings['type'], 
    '#options' => _reach_social_field_get_types($settings['service']),
    '#multiple' => TRUE,
  );

  return $form;
}


/**
 * Helper function returns a keyed array of the available services.
 */
function _reach_social_field_get_services($type = NULL, $allowed = NULL) {
  $return = array();
  foreach (reach_social_field_services() as $key => $service) {
    if (!is_array($allowed) || !count($allowed) || in_array($key, $allowed)) {
      if (is_array($type)) {
        foreach ($type as $type_name) {
          if (is_array($service[$type_name])) {
            $return[$key] = ucfirst($key);
          }
        } // foreach
      } else {
        $return[$key] = ucfirst($key);  
      }
    } // if ($allowed)
  } // foreach
  return $return;
}


/**
 * Helper function returns a keyed array of the available types of social network entities.
 */
function _reach_social_field_get_types($service = NULL, $allowed = NULL) {
  $return = array();
  foreach (reach_social_field_services() as $key => $item_service) {
    if (!$service || (is_array($service) && in_array($key, $service))) {
      foreach ($item_service as $key_type => $type) {
        if (!is_array($allowed) || !count($allowed) || in_array($key, $allowed)) {
          $return[$key_type] = $type['label'];
        }
      }
    }
  }
  return $return;
}


/**
 * Implements hook_field_validate().
 *
 * This hook gives us a chance to validate content that's in our
 * field. We're really only interested in the $items parameter, since
 * it holds arrays representing content in the field we've defined.
 * We want to verify that the items only contain RGB hex values like
 * this: #RRGGBB. If the item validates, we do nothing. If it doesn't
 * validate, we add our own error notification to the $errors parameter.
 *
 * @see reach_social_field_field_widget_error()
 */
/*function reach_social_field_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    if (!empty($item['rgb'])) {
      if (! preg_match('@^#[0-9a-f]{6}$@', $item['rgb'])) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'reach_social_field_invalid',
          'message' => t('Color must be in the HTML format #abcdef.'),
        );
      }
    }
  }
}*/


/**
 * Implements hook_field_is_empty().
 *
 * hook_field_is_emtpy() is where Drupal asks us if this field is empty.
 * Return TRUE if it does not contain data, FALSE if it does. This lets
 * the form API flag an error when required fields are empty.
 */
function reach_social_field_field_is_empty($item, $field) {
  return empty($item['value']);
}

/**
 * Implements hook_field_formatter_info().
 */
function reach_social_field_field_formatter_info() {
  return array(
    'reach_social_field_plain' => array(
      'label' => t('Display the id as plain text'),
      'field types' => array('reach_social_field'),
    ),
    'reach_social_field_link' => array(
      'label' => t('Display as the title with a link'),
      'field types' => array('reach_social_field'),
    ),
    'reach_social_field_url' => array(
      'label' => t('Display as the plain URL'),
      'field types' => array('reach_social_field'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function reach_social_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
  
    case 'reach_social_field_plain':
      
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#type' => 'html_tag',
          '#tag' => 'div',
          '#value' => $item['id'],
        );
      }
      break;
      
    case 'reach_social_field_link':
      
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#type' => 'html_tag',
          '#tag' => 'div',
          '#value' => l($item['label'] ? $item['label'] : $entity->title, $item['url']),
        );
      }
      break;
    
    case 'reach_social_field_url':
      
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#type' => 'html_tag',
          '#tag' => 'div',
          '#value' => $entity->title, $item['url'],
        );
      }
      break;

  }

  return $element;
}

/**
 * Implements hook_field_widget_info().
 */
function reach_social_field_field_widget_info() {
  return array(
    'reach_social_field_text' => array(
      'label' => t('Textfield'),
      'field types' => array('reach_social_field'),
    ),
    'reach_social_field_hidden' => array(
      'label' => t('Hidden'),
      'field types' => array('reach_social_field'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function reach_social_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $value = isset($items[$delta]['value']) ? $items[$delta]['value'] : '';
dpm($value);
dpm( $instance['widget']['settings']);
  $widget = $element;
  $widget['#delta'] = $delta;

  switch ($instance['widget']['type']) {

    case 'reach_social_field_text':
        
        $options = _reach_social_field_get_services($instance['widget']['settings']['type'], $instance['widget']['settings']['service']);
        if (count($options) > 1) {
          $widget['service'] = array(
            '#type' => 'select', 
            '#title' => t('Service'), 
            '#description' => t('Select the source of the content.'),
            '#default_value' => $value['service'], 
            '#options' => $options,
          );
        }
        elseif (count($options) == 1) {
          $options = array_keys($options);
          $widget['service'] = array(
            '#type' => 'value', 
            '#value' => $options[0],
          );
        }
        
        
        $options = _reach_social_field_get_types($instance['widget']['settings']['service'], $instance['widget']['settings']['type']);
        if (count($options) > 1) {
          $widget['type'] = array(
            '#type' => 'select', 
            '#title' => t('Type'),
            '#description' => t('Select the type of content this is.'),
            '#default_value' => $value['type'], 
            '#options' => $options,
          );
        }
        elseif (count($options) == 1) {
          $options = array_keys($options);
          $widget['type'] = array(
            '#type' => 'value', 
            '#value' => $options[0],
          );
        }
        
        $widget['id'] = array(
          '#type' => 'textfield', 
          '#title' => t('ID'),
          '#description' => t('Enter the id or URL of the item.'),
          '#default_value' => $value['id'], 
        );
      
      break;
      
    case 'reach_social_field_hidden':
      $widget += array(
        '#type' => 'hidden',
        '#value' => $value,
      );
      break;

  }

  $element['value'] = $widget;

  return $element;
}



/**
 * Implements hook_field_widget_error().
 *
 * hook_field_widget_error() lets us figure out what to do with errors
 * we might have generated in hook_field_validate(). Generally, we'll just
 * call form_error().
 *
 * @see reach_social_field_field_validate()
 * @see form_error()
 */
/*function reach_social_field_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'reach_social_field_invalid':
      form_error($element, $error['message']);
      break;
  }
}*/

