<?php
// $Id:$

/**
 * @file
 * Module that creates blocks for common page template elements so they can be
 * moved around in the admin interface.
 *
 * @todo: This needs an alteration to the default site information form for
 * configuration outside of the theme's info file.
 */

/**
 * Implements hook_theme()
 */
function block_everything_theme() {
  return array(
    'block__block_everything' => array(
      'render element' => 'elements',
    ),
    'block_everything_site_name' => array(
      'render element' => 'element',
    ),
    'block_everything_site_slogan' => array(
      'render element' => 'element',
    ),
    'block_everything_logo' => array(
      'render element' => 'element',
    ),
    'block_everything_page_title' => array(
      'render element' => 'element',
    ),
    'block_everything_copyright' => array(
      'render element' => 'element',
    ),
    'block_everything_paid_for_by' => array(
      'render element' => 'element',
    ),
    'block_everything_powered_by' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Context plugins.
 */
function block_everything_context_plugins() {
  $plugins = array();

  $plugins['context_reaction_page_title'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'block_everything') .'/plugins',
      'file' => 'context_reaction_page_title.inc',
      'class' => 'context_reaction_page_title',
      'parent' => 'context_reaction',
    ),
  );
  return $plugins;
}

/**
 * Implementation of hook_context_registry()
 */
function block_everything_context_registry() {
  $registry = array();

  $registry['reactions'] = array(
    'page_title' => array(
      'title' => t('Page Title Switcher'),
      'description' => t('Control additional page title options.'),
      'plugin' => 'context_reaction_page_title',
    ),
  );

  return $registry;
}

/**
 * Implements hook_block_info()
 */
function block_everything_block_info() {
  $blocks = array();
  global $user;
  $theme = !empty($user->theme) ? $user->theme : variable_get('theme_default');
  $settings = theme_get_setting('block_everything', $theme);

  // Only display the blocks if the default theme supports them
  if (isset($settings['site_name'])) {
    $blocks['site_name'] = array(
      'info' => 'Site name',
      'cache' => DRUPAL_CACHE_GLOBAL,
      'status' => 1,
      'region' => $settings['site_name'],
    );
  }

  if (isset($settings['site_slogan'])) {
    $blocks['site_slogan'] = array(
      'info' => 'Site slogan',
      'cache' => DRUPAL_CACHE_GLOBAL,
      'status' => 1,
      'region' => $settings['site_slogan'],
    );
  }

  if (isset($settings['logo'])) {
    $blocks['logo'] = array(
      'info' => 'Site logo',
      'cache' => DRUPAL_CACHE_GLOBAL,
      'status' => 1,
      'region' => $settings['logo'],
    );
  }

  if (isset($settings['page_title'])) {
    $blocks['page_title'] = array(
      'info' => 'Page Title',
      'cache' => DRUPAL_CACHE_GLOBAL,
      'status' => 1,
      'region' => $settings['page_title'],
    );
  }

  $blocks['copyright'] = array(
    'info' => 'Copyright info',
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['paid_for_by'] = array(
    'info' => 'Paid for by block',
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['powered_by'] = array(
    'info' => 'Powered by block',
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_themes_enabled()
 *
 * The purpose of this is to properly set the default regions when a theme is
 * updated and enabled.
 */
function block_everything_themes_enabled($theme_list) {
  foreach($theme_list as $theme) {
    $settings = theme_get_setting('block_everything', $theme);
    $theme_setting_name = array(
      'site_name' => 'toggle_name',
      'site_slogan' => 'toggle_slogan',
      'logo' => 'default_logo_path',
      'page_title' => 'toggle_page_title',
    );

    // Get the block_everything blocks for this theme
    $result = db_query("SELECT * FROM {block} WHERE theme = :theme and module = 'block_everything'", array(':theme' => $theme), array('fetch' => PDO::FETCH_ASSOC));
    foreach ($result as $block) {
      // If the block is disabled, check to make sure the theme supports it and
      // enable it in the default region.  If the theme does not support
      // block_everything, disable the blocks.
      if (!$block['status'] || !$settings) {
        $region = (theme_get_setting($theme_setting_name[$block['delta']], $theme) && isset($settings[$block['delta']])) ? $settings[$block['delta']] : BLOCK_REGION_NONE;
        $status = isset($settings[$block['delta']]) ? 1 : 0;

        db_update('block')
          ->fields(array(
            'region' => $region,
            'status' => $status,
          ))
          ->condition('theme', $theme)
          ->condition('delta', $block['delta'])
          ->condition('module', 'block_everything')
          ->execute();

        // Invoke a hook to inform other modules that the block was just
        // modified.
        module_invoke_all('block_everything_modified_block', $block);
      }
    }
  }
}

/**
 * Implements hook_block_configure()
 */
function block_everything_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case 'site_name':
      $form['block_everything'] = array(
        '#type' => 'textfield',
        '#title' => t('Site name'),
        '#default_value' => variable_get('site_name', 'Drupal'),
      );
      break;
    case 'site_slogan':
      $form['block_everything'] = array(
        '#type' => 'textfield',
        '#title' => t('Site slogan'),
        '#default_value' => variable_get('site_slogan', ''),
      );
      break;
    case 'copyright':
      $form['block_everything'] = array(
        '#type' => 'textfield',
        '#title' => t('Copyright by'),
        '#default_value' => variable_get('block_everything_copyright', variable_get('site_name', '')),
      );
      $form['block_everything_text'] = array(
        '#type' => 'textfield',
        '#title' => t('Copyright text'),
        '#default_value' => variable_get('block_everything_copyright_text', 'All Rights Reserved.'),
      );
      break;
    case 'paid_for_by':
      $form['block_everything'] = array(
        '#type' => 'textfield',
        '#title' => t('Paid for by'),
        '#default_value' => variable_get('block_everything_paid_for_by', variable_get('site_name', '')),
      );
      break;
    case 'powered_by':
      $form['block_everything'] = array(
        '#type' => 'textfield',
        '#title' => t('Powered by'),
        '#default_value' => variable_get('block_everything_powered_by', 'Albatross Reach'),
      );
      $form['block_everything_link'] = array(
        '#type' => 'textfield',
        '#title' => t('Powered by Link'),
        '#default_value' => variable_get('block_everything_powered_by_link', 'albatrossdigital.com'),
      );
      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function block_everything_block_save($delta = '', $edit = array()) {
  global $user;
  $theme = !empty($user->theme) ? $user->theme : variable_get('theme_default');
  $settings = variable_get('theme_settings', array());

  switch ($delta) {
    case 'site_name':
      variable_set('site_name', $edit['block_everything']);
      $settings['toggle_name'] = $edit['regions'][$theme] == BLOCK_REGION_NONE ? 0 : 1;
      break;
    case 'site_slogan':
      variable_set('site_slogan', $edit['block_everything']);
      $settings['toggle_slogan'] = $edit['regions'][$theme] == BLOCK_REGION_NONE ? 0 : 1;
      break;
    case 'copyright':
      variable_set('block_everything_copyright', $edit['block_everything']);
      variable_set('block_everything_copyright_text', $edit['block_everything_text']);
      break;
    case 'paid_for_by':
      variable_set('block_everything_paid_for_by', $edit['block_everything']);
      break;
    case 'powered_by':
      variable_set('block_everything_powered_by', $edit['block_everything']);
      variable_set('block_everything_powered_by_link', $edit['block_everything_link']);
      break;

  }
  variable_set('theme_settings', $settings);
}

/**
 * Implements hook_block_view()
 */
function block_everything_block_view($delta = '') {
  $block = array();
  global $theme;

  switch ($delta) {
    case 'site_name':
      $block['content'] = filter_xss_admin(variable_get('site_name', 'Drupal'));
      break;
    case 'site_slogan':
      $block['content'] = filter_xss_admin(variable_get('site_slogan', ''));
      break;
    case 'logo':
      if (!$logo = theme_get_setting('logo_path')) {
        $logo = theme_get_setting('logo');
      }

      if (!empty($logo)) {
        // [1]
        // Remove the base URL from the result returned by theme_get_setting('logo').
        // If you don't need the relative path, you can remove this code.
        if (strpos($logo, $base_url) === 0) {
          $logo = drupal_substr($logo, drupal_strlen($base_url));
        }
      }
      //$path = theme_get_setting('logo_path', $theme) ? drupal_get_path('theme', $theme) . '/' . theme_get_setting('default_logo_path', $theme) : '';
      $block['content'] = $logo;
      break;
    case 'page_title':
      $block['content'] = drupal_get_title();
      break;
    case 'copyright':
      $block['content'] = variable_get('block_everything_copyright', variable_get('site_name', ''));
      break;
    case 'paid_for_by':
      $block['content'] = variable_get('block_everything_paid_for_by', variable_get('site_name', ''));
      break;
    case 'powered_by':
      $block['content'] = l(variable_get('block_everything_powered_by', 'Albatross Reach'), variable_get('block_everything_powered_by_link', 'http://albatrossdigital.com'));
      break;

  }
  return $block;
}

/**
 * Alters the block configuration form to hide the title
 */
function block_everything_form_block_admin_configure_alter(&$form, &$form_state, $form_id) {
  if ($form['module']['#value'] == 'block_everything') {
    $form['settings']['title']['#access'] = FALSE;
  }
}

/**
 * Alters the main block admin page to add a submit handler for block_everything
 */
function block_everything_form_block_admin_display_form_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'block_everything_admin_display_form_submit';
}

/**
 * Updates the theme settings depending on the region for block_everything blocks.
 */
function block_everything_admin_display_form_submit($form, &$form_state) {
  foreach ($form_state['values']['blocks'] as $block) {
    if ($block['module'] == 'block_everything') {
      $delta = $block['delta'];
      $settings = variable_get('theme_settings', array());
      switch ($delta) {
        case 'site_name':
          $settings['toggle_name'] = $block['region'] == BLOCK_REGION_NONE ? 0 : 1;
          break;
        case 'site_slogan':
          $settings['toggle_slogan'] = $block['region'] == BLOCK_REGION_NONE ? 0 : 1;
          break;
      }
      variable_set('theme_settings', $settings);
    }
  }
}

/**
 * Implements hook_process_page()
 *
 * Unsets the items that would otherwise be printed to the page
 */
function block_everything_process_page(&$vars) {
  global $theme;
  $settings = theme_get_setting('block_everything', $theme);

  if ($settings) {
    foreach($settings as $key => $region) {
      $vars[$key] = NULL;
    }
  }
}

/**
 * Outputs the theming for the blocks.
 */
function theme_block__block_everything($vars) {
  global $theme;
  if (!theme_get_setting('block_everything', $theme) || $vars['content'] == '') {
    return '';
  }

  // Add necessary CSS.
  drupal_add_css(drupal_get_path('module', 'block_everything') . '/block_everything.css');

  // Create a new class array
  $classes = array('page-element', strtr($vars['block']->delta, '_', '-') . '-wrapper');

  // Iterate through the old class array and add classes that do not include
  // block in their name.  e.g. block and block-block-everything
  foreach($vars['classes_array'] as $key => $class) {
    if (strpos($class, 'block') === FALSE) {
      $classes[] = $vars['classes_array'][$key];
    }
  }

  $output = '<div class="' . implode(' ', $classes) . '">';
  $output .= render($vars['title_prefix']);
  $output .= render($vars['title_suffix']);

  $output .= theme('block_everything_' . $vars['block']->delta, $vars);

  $output .= '</div>';

  return $output;
}

/**
 * Returns markup for the site name.
 *
 * The site name is within either a <h1> or a <p> tag dependent on $is_front for
 * SEO purposes.
 */
function theme_block_everything_site_name($vars) {
  if(empty($vars['elements']['#markup'])) {
    $name = $vars['elements']['content']['#markup'];//$vars['content'];
  }
  else {
    $name = $vars['elements']['#markup'];
  }
  $is_front = $vars['is_front'];

  $output = $is_front ? '<h1' : '<p';
  $output .= ' id="site-name"';
  $output .= ' class="site-name ' . ($is_front ? 'site-name-front' : '') . '">';
  $output .= l('<span>' . $name . '</span>', '', array('attributes' => array('title' => t('Home'), 'rel' => 'home'), 'html' => TRUE));
  $output .= $is_front ? '</h1>' : '</p>';

  return $output;
}

/**
 * Returns markup for the site's slogan
 */
function theme_block_everything_site_slogan($vars) {
  if(empty($vars['elements']['#markup'])) {
    $slogan = $vars['elements']['content']['#markup'];//$vars['content'];
  }
  else {
    $slogan = $vars['elements']['#markup'];
  }
  
  $output = '<p id="site-slogan" class="site-slogan">' . $slogan . '</p>';

  return $output;
}

/**
 * Returns markup for the site's logo
 */
function theme_block_everything_logo($vars) {
  if(empty($vars['elements']['#markup'])) {
    $logo_path = $vars['elements']['content']['#markup'];//$vars['content'];
  }
  else {
    $logo_path = $vars['elements']['#markup'];
  }
  $home = t('Home');
  $image_vars = array(
    'path' => $logo_path,
    'alt' => $home,
    'title' => $home,
  );

  $image = theme('image', $image_vars);
  $output = l($image, '', array('attributes' => array('rel' => 'home', 'id' => 'logo', 'class' => 'logo'), 'html' => TRUE));

  return $output;
}

/**
 * Returns markup for the page title
 */
function theme_block_everything_page_title($vars) {
  //$page_title = $vars['elements']['content']['#markup'];//$vars['content'];
  if(empty($vars['elements']['#markup'])) {
    $page_title = $vars['elements']['content']['#markup'];//$vars['content'];
  }
  else {
    $page_title = $vars['elements']['#markup'];
  }
  if ($plugin = context_get_plugin('reaction', 'page_title')) {
    $plugin->execute($page_title);
  }
  $output = '<h1 id="page-title">' . $page_title . '</h1>';
  
  return $output;
}

/**
 * Returns markup for the site's copyright info
 */
function theme_block_everything_copyright($vars) {
  //$copyright = $vars['elements']['content']['#markup'];//$vars['content'];
  if(empty($vars['elements']['#markup'])) {
    $copyright = $vars['elements']['content']['#markup'];//$vars['content'];
  }
  else {
    $copyright = $vars['elements']['#markup'];
  }
  $output = '<p>&copy' . date('Y') . ' ' . $copyright . '&nbsp' . variable_get('block_everything_copyright_text') . '</p>';

  return $output;
}

/**
 * Returns markup for the site's paid for by information
 */
function theme_block_everything_paid_for_by($vars) {
  //$paid_for_by = $vars['elements']['content']['#markup'];//$vars['content'];
  if(empty($vars['elements']['#markup'])) {
    $paid_for_by = $vars['elements']['content']['#markup'];//$vars['content'];
  }
  else {
    $paid_for_by = $vars['elements']['#markup'];
  }
  $output = '<p>Paid for by ' . $paid_for_by . '</p>';

  return $output;
}

/**
 * Returns markup for the site's paid for by information
 */
function theme_block_everything_powered_by($vars) {
  //$powered_by = $vars['elements']['content']['#markup'];//$vars['content'];
  if(empty($vars['elements']['#markup'])) {
    $powered_by = $vars['elements']['content']['#markup'];//$vars['content'];
  }
  else {
    $powered_by = $vars['elements']['#markup'];
  }

  $output = '<p class="clearfix"><span class="powered-text">Powered by</span> <span class="powered-logo">' . $powered_by . '</span></p>';

  return $output;
}



