<?php
// $Id: feeds_selfnode_processor.module,v 1.1.2.1 2011/02/01 09:53:28 twistor Exp $

function feeds_media_processor_feeds_plugins() {
  $info = array();
  $info['FeedsMediaProcessor'] = array(
    'name' => 'Media File processor',
    'description' => 'Populate fields on a media file entity.',
    'help' => 'Update the fields of a media file entity from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'FeedsMediaProcessor',
      'file' => 'FeedsMediaProcessor.inc',
      'path' => drupal_get_path('module', 'feeds_media_processor'),
    ),
  );
  
  return $info;
}


//function feeds_media_processor_form_feeds_import_form_alter(&$form, &$form_state, $form_id){
  /*$form['mid'] = array(
    '#type' => 'hidden',
    '#default_value' => arg(2),
  );*/
  
  // Save the mid as a session variable so we can create the proper relations.
  // TODO: better solution?
  //$_SESSION['current_mid'] = arg(2);
  //dpm($_SESSION['mid']);
//}
