<?php
/**
 * @file
 * reach_form.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function reach_form_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'language_content_type_form';
  $strongarm->value = '0';
  $export['language_content_type_form'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'menu_options_form';
  $strongarm->value = array(
    0 => 'main-menu',
  );
  $export['menu_options_form'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'menu_parent_form';
  $strongarm->value = 'main-menu:0';
  $export['menu_parent_form'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_options_form';
  $strongarm->value = array(
    0 => 'status',
  );
  $export['node_options_form'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_preview_form';
  $strongarm->value = '1';
  $export['node_preview_form'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_submitted_form';
  $strongarm->value = 0;
  $export['node_submitted_form'] = $strongarm;

  return $export;
}
