<?php
/**
 * @file
 */


include_once('reach_administration.features.inc');

/**
 * Implements hook_block_info().
 */
function reach_administration_block_info() {
  $blocks['create_new'] = array(
    'info' => t('Create new...'),
  );
  return $blocks;
}



/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function reach_administration_block_configure($delta = '') {
   $form = array();
   switch ($delta) {
    case 'create_new':
      $info = entity_get_info('node');
      $options = array();
      foreach ($info['bundles'] as $type => $bundle_info) {
        if (user_access ('create ' . $type . ' content')) {
          $options[$type] = $bundle_info['label'];
        } //if
      } //foreach
      $form['limit_bundle'] =  array(
        '#type' => 'checkboxes',
        '#options' => $options,
        '#title' => t('Entities to include'),
        '#default_value' => variable_get('reach_administration_block_bundles', array_keys($options)),
      );
      dpm($form);
      break;
   }   
   return $form;
}

/**
 * Implements hook_block_save().
 *
 * This hook declares how the configured options for a block
 * provided by this module are saved.
 */
function reach_administration_block_save($delta = '', $edit = array()) {
  dpm($edit);
  dpm('---------------------------');
  dpm(array_keys(array_filter($edit['limit_bundle'])));
  dpm('------------))))))))))))))))))))');
  variable_set('reach_administration_block_bundles', array_keys(array_filter($edit['limit_bundle'])));
}


/**
 * Implements hook_block_view().
 */
function reach_administration_block_view($delta = '') {
  switch ($delta) {
    
    // Build the html/text preview tabs
    
    case 'create_new':
      $block['title'] = t('Create new...');
      // TODO: we should really cycle through all of the content types that the person has permission to create
      $info = entity_get_info('node');
      $links = array();
      $included = variable_get('reach_administration_block_bundles', array_keys($options));
      foreach ($info['bundles'] as $type => $bundle_info) {
        if (user_access ('create ' . $type . ' content') && in_array($type, $included)) {
          $links[$type] = array(
            'href'  => 'node/add/' . $type,
            'title' => $bundle_info['label'],
            'attributes' => array('class' => array('create-' . $type)),
          );
        } //if
      } //foreach
      
      if (module_exists('party') && user_access('create parties')) {
        $links['party'] = array(
          'href'  => 'party/add/individual',
          'title' => t('Create Contact'),
          'attributes' => array('class' => array('create-contact')),
        );
      }
      
      $block['content'] = theme('links', array('links' => $links, 'attributes' => array('class' => array('create', 'item-list')) ));
      
      //$block['content'] = '<ul class="item-list create"><li class="first create-blog"><a class="create-blog" href="/node/add/blog">Blog Post</a></li><li class="first create-page"><a href="/node/add/page">Page</a></li><li class="create-form"><a href="/node/add/form">Form</a></li><li class="create-donation"><a href="/node/add/donation">Donation Page</a></li><li class="create-issue"><a href="/node/add/issue">Issue Page</a></li><li class="create-contact"><a href="/party/add/individual">Contact</a></li></ul>';

      break;
  }
  return $block;
}
