<?php
// $Id: feeds_selfnode_processor.module,v 1.1.2.1 2011/02/01 09:53:28 twistor Exp $

function feeds_oauthconnector_fetcher_feeds_plugins() {
  dpm('asdf');
  $info = array();
  $info['FeedsOAuthConnectorFetcher'] = array(
    'name' => 'Oauth Connector Fetcher',
    'description' => 'Load a feed after Oauth autentication.',
    //'help' => 'Update the fields of a party entity from parsed content.',
    'handler' => array(
      'parent' => 'FeedsFetcher',
      'class' => 'FeedsOAuthConnectorFetcher',
      'file' => 'FeedsOAuthConnectorFetcher.inc',
      'path' => drupal_get_path('module', 'feeds_oauthconnector_fetcher'),
    ),
  );
  
  
  return $info;
}


//function feeds_oauthconnector_fetcher_form_feeds_import_form_alter(&$form, &$form_state, $form_id){
  /*$form['mid'] = array(
    '#type' => 'hidden',
    '#default_value' => arg(2),
  );*/
  
  // Save the mid as a session variable so we can create the proper relations.
  // TODO: better solution?
  //$_SESSION['current_mid'] = arg(2);
  //dpm($_SESSION['mid']);
//}
