<?php
/**
 * @file
 * Code for the Reach Donation feature.
 */

include_once('reach_donation.features.inc');


/**
 * Implementatation of reach_webform_submitted.
 *
 * Save the relation.
 */
function reach_donation_reach_webform_submitted($party, $node, $entity) {
  if ($node->type == 'donation') {
    $endpoints = array(
      array('type' => 'party', 'id' => $party->pid),
      array('type' => 'node', 'id' => $node->nid),
      array('type' => 'webform_submission_entity', 'id' => $entity->wsid),
    );
    
    foreach($entity->data as $cid => $component) {
      $form_key = $node->webform['components'][$cid]['form_key'];
      if ($node->webform['components'][$cid]['type'] == 'stripe') {
        $donation = $component['value'];
        break;
      }
    } // foreach

    $points = $node->reach_webform['points'] * $donation['amount'];
    
    $data = array();
    $data['field_amount'][LANGUAGE_NONE][0]['value'] = $donation['amount'];
    //$data['field_payment_method'][LANGUAGE_NONE][0]['value'] = $donation['method'];
    //$data['field_payment_status'][LANGUAGE_NONE][0]['value'] = $donation['status'];
    //$data['field_payment_id'][LANGUAGE_NONE][0]['value'] = $donation['id'];
    
    reach_crm_save_relation('donation', $endpoints, $points, $data);
  }
}
